#!/usr/bin/env python3
#
# Turns a local 8 KB EPROM dump (e.g. the real PRCX-18 v1.9.0, 2764) into
# the VHDL package tb_prcx18_lockstep.vhd loads it from:
#
#   python3 gen_rom_pkg.py prcx18.bin > prcx18_rom_pkg.vhd
#
# The ROM image is copyrighted and not part of this (public) repo, and so
# is the generated package: write it somewhere outside git (run_prcx18_
# lockstep.sh puts it in its own gitignored run directory).
import sys


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <rom.bin>", file=sys.stderr)
        sys.exit(1)
    rom = open(sys.argv[1], "rb").read()
    if len(rom) != 8192:
        print(f"error: expected 8192 bytes, got {len(rom)}", file=sys.stderr)
        sys.exit(1)
    print("-- Generated by boards/cora-z7-07s/sim/gen_rom_pkg.py -- local only, do not commit.")
    print("LIBRARY IEEE;")
    print("USE IEEE.std_logic_1164.ALL;")
    print("USE work.test_program_pkg.ALL;")
    print()
    print("PACKAGE prcx18_rom_pkg IS")
    print("  CONSTANT c_prcx18_rom : t_mem_array(0 TO 8191) := (")
    lines = []
    for i in range(0, 8192, 16):
        lines.append("    " + ", ".join(f'X"{b:02X}"' for b in rom[i:i + 16]))
    print(",\n".join(lines))
    print("  );")
    print("END prcx18_rom_pkg;")


if __name__ == "__main__":
    main()
